name: circlebox_flutter
description: Flutter bridge for CircleBox native crash context SDK.
version: 0.1.0
homepage: https://github.com/jeremiahseun/circlebox

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.circlebox.flutter_circlebox
        pluginClass: CircleboxFlutterPlugin
      ios:
        pluginClass: CircleboxFlutterPlugin
